[package]
name = "rust_rpi_lora"
version = "0.1.0"
authors = ["jack <jackorton32@gmail.com>"]
edition = "2018"

[dependencies]
joy = "0.1.2"
rppal = { git = "https://github.com/golemparts/rppal" }
byteorder = "1.3.1"
